# Generated by Django 5.2.4 on 2025-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("under_review", "Under Review"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
