# Generated by Django 5.2.4 on 2025-07-27 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0003_feedback_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="description",
        ),
        migrations.AlterField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="boards", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
