# Generated by Django 5.2.4 on 2025-07-28 03:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0004_alter_board_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="board",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the board's purpose"
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Public boards are visible to all users, private boards require membership",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have access to this board",
                related_name="boards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="name",
            field=models.CharField(
                help_text="Name of the feedback board",
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="The user who wrote this comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                help_text="The comment content",
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="feedback",
            field=models.ForeignKey(
                help_text="The feedback this comment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="feedback_app.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="author",
            field=models.ForeignKey(
                help_text="The user who created this feedback",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="board",
            field=models.ForeignKey(
                help_text="The board this feedback belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="feedback_app.board",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="content",
            field=models.TextField(
                help_text="Detailed description of the feedback",
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                help_text="Priority level of the feedback",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("under_review", "Under Review"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="open",
                help_text="Current status of the feedback",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for categorizing this feedback",
                related_name="feedbacks",
                to="feedback_app.tag",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="title",
            field=models.CharField(
                help_text="Brief title describing the feedback",
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have upvoted this feedback",
                related_name="upvoted_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Tag name for categorizing feedback",
                max_length=50,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("contributor", "Contributor"),
                ],
                default="contributor",
                help_text="User's role determines their permissions in the system",
                max_length=20,
            ),
        ),
    ]
